# Generated by Django 4.0.3 on 2022-03-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_customers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_key',
            field=models.UUIDField(null=True),
        ),
    ]
