# Generated by Django 4.0.3 on 2022-03-03 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_customers_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_key',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
