# Generated by Django 4.0.3 on 2022-03-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_customers_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_key',
            field=models.CharField(default='x', max_length=8, null=True),
        ),
    ]
