# Generated by Django 4.0.3 on 2022-03-03 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_customers_customer_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='customer_key',
        ),
    ]
