# Generated by Django 4.0.3 on 2022-03-03 23:03

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_customers_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=4, max_length=4, prefix='id_', primary_key=True, serialize=False),
        ),
    ]
