# Generated by Django 4.0.3 on 2022-03-04 15:03

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_customers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=4, max_length=4, prefix='SE', primary_key=True, serialize=False),
        ),
    ]
